"""Add V2 models

Revision ID: 18bd2eb49ebb
Revises: 7272cefb04d4
Create Date: 2026-03-15 12:28:13.614795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bd2eb49ebb'
down_revision = '7272cefb04d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=64), nullable=True),
    sa.Column('years_in_service', sa.String(length=64), nullable=True),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('fatal_incidents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aircraft_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_variant_variant_name'), ['variant_name'], unique=False)

    op.create_table('incident_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('report_url', sa.String(length=512), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('tagged_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_tag_system_name'), ['system_name'], unique=False)

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_date'))

    with op.batch_alter_table('system_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_tag_system_name'))

    op.drop_table('system_tag')
    op.drop_table('report_analysis')
    op.drop_table('incident_source')
    with op.batch_alter_table('aircraft_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_variant_variant_name'))

    op.drop_table('aircraft_variant')
    # ### end Alembic commands ###
