"""Initial schema

Revision ID: 76d481f2c04c
Revises: 
Create Date: 2025-12-08 15:45:41.861728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d481f2c04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('icao_code', sa.String(length=10), nullable=True),
    sa.Column('years_in_service', sa.Integer(), nullable=True),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('fatal_incidents', sa.Integer(), nullable=True),
    sa.Column('total_fatalities', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_icao_code'), ['icao_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_model_name'), ['model_name'], unique=True)

    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_model', sa.String(length=128), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_aircraft_model'), ['aircraft_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_email'), ['user_email'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asn_url', sa.String(length=256), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_email'))
        batch_op.drop_index(batch_op.f('ix_request_aircraft_model'))

    op.drop_table('request')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_model_name'))
        batch_op.drop_index(batch_op.f('ix_aircraft_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_aircraft_icao_code'))

    op.drop_table('aircraft')
    # ### end Alembic commands ###
