"""add_registration_to_incident

Revision ID: 9c8c6debed21
Revises: 3a91c2c7d1e4
Create Date: 2026-03-30 21:08:36.323248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8c6debed21'
down_revision = '3a91c2c7d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_incident_registration'), ['registration'], unique=False)

    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_source_source_name_source_record_id')

    with op.batch_alter_table('jasc_mapping', schema=None) as batch_op:
        batch_op.drop_index('ix_jasc_mapping_jasc_code')
        batch_op.create_index(batch_op.f('ix_jasc_mapping_jasc_code'), ['jasc_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jasc_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jasc_mapping_jasc_code'))
        batch_op.create_index('ix_jasc_mapping_jasc_code', ['jasc_code'], unique=False)

    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.create_index('ix_incident_source_source_name_source_record_id', ['source_name', 'source_record_id'], unique=False)

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_registration'))
        batch_op.drop_column('registration')

    # ### end Alembic commands ###
