"""Add discrepancy fields to Incident

Revision ID: aba86b120c64
Revises: 6c3d9a1e2f0b
Create Date: 2026-04-05 22:11:08.905663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba86b120c64'
down_revision = '6c3d9a1e2f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_state', schema=None) as batch_op:
        batch_op.drop_index('ix_import_state_source_name')
        batch_op.create_index(batch_op.f('ix_import_state_source_name'), ['source_name'], unique=True)

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_discrepancy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_details', sa.JSON(), nullable=True))

    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_source_source_name_source_record_id')

    with op.batch_alter_table('jasc_mapping', schema=None) as batch_op:
        batch_op.drop_index('ix_jasc_mapping_jasc_code')
        batch_op.create_index(batch_op.f('ix_jasc_mapping_jasc_code'), ['jasc_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jasc_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jasc_mapping_jasc_code'))
        batch_op.create_index('ix_jasc_mapping_jasc_code', ['jasc_code'], unique=False)

    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.create_index('ix_incident_source_source_name_source_record_id', ['source_name', 'source_record_id'], unique=False)

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('discrepancy_details')
        batch_op.drop_column('has_discrepancy')

    with op.batch_alter_table('import_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_state_source_name'))
        batch_op.create_index('ix_import_state_source_name', ['source_name'], unique=False)

    # ### end Alembic commands ###
