"""Add index to IncidentSource.source_name

Revision ID: be4e7bb8751a
Revises: 18bd2eb49ebb
Create Date: 2026-03-15 12:28:45.396957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4e7bb8751a'
down_revision = '18bd2eb49ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_source_source_name'), ['source_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_source_source_name'))

    # ### end Alembic commands ###
